spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  exchanges:
    product: exchange.product
  queues:
    order:
      productCreated: queue.order.productCreated
  routing-keys:
    product:
      created: product.created

server:
  port: 8090